### ISSUE TITLE
Bot doesn't respond to messages

### ISSUE THREAD

**Issue by Recouse** [akalongman/php-telegram-bot#141] opened 2016-04-14 16:50 UTC
Error in **hook.php**:
`Longman\TelegramBot\Exception\TelegramException: Input is empty! in .../vendor/longman/telegram-bot/src/Telegram.php:414 Stack trace: #0 .../hook.php(52): Longman\TelegramBot\Telegram->handle() #1 {main}`

**Comment by noplanman** [comment] 2016-04-14 17:00
Did you get this when opening the URL to your **hook.php** file?
When using the webHook, there is no need for you to open it directly, it only needs to be accessed by Telegram.

**Comment by Recouse** [comment] 2016-04-14 17:03
I opened just for test. Because bot doesn't respond to messages.

**Comment by noplanman** [comment] 2016-04-14 17:51
Have you correctly set the webHook using the **set.php** example file?

Check here to make sure that you've set it up properly 👍 
https://github.com/akalongman/php-telegram-bot#webhook-installation

**Comment by CrazyRedScorp** [comment] 2016-04-14 18:02
Maybe you need to add the next line to the file composer.json:
```
"longman/telegram-bot": "*"
```
and run
```
composer update
```
https://github.com/akalongman/php-telegram-bot#require-this-package-with-composer

**Comment by CrazyRedScorp** [comment] 2016-04-14 19:31
##### Example: #####
##### 1) my "set.php" #####
```
<?php
// Load composer
require __DIR__ . '/vendor/autoload.php';

$API_KEY = 'ID:KEY';
$BOT_NAME = 'mycats_bot';
$hook_url = 'https://mydomain/hook.php';
$path_certificate = @'/var/www/html/mydomain.pem';
try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);

    // Set webhook
    //$result = $telegram->setWebHook($hook_url);

    // Uncomment to use certificate
    $result = $telegram->setWebHook($hook_url, $path_certificate);

    if ($result->isOk()) {
        echo $result->getDescription();
    }
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    echo $e;
}
```
Accept: $BOT_NAME = 'mycats_bot';
Wrong: $BOT_NAME = 'mycats';

##### 2) And my SSL-key file "mydomain.pem" #####
```
-----BEGIN CERTIFICATE-----
root certificate (from file "root.crt")
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
intermediate certificate (from file "intermediate.crt")
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
mydomain certificate (from file "mydomain.crt")
-----END CERTIFICATE-----
```
I got a free certificate for 1 year on site https://startssl.com/

##### Attention! #####
If the certificate is invalid or there are some problems with php files - 'telegram' will not send any messages !!!

**Comment by Recouse** [comment] 2016-04-15 01:58
I correctly set webHook. 2 days ago my bot worked fine, but now he isn't working.

**Comment by CrazyRedScorp** [comment] 2016-04-15 06:12
What's in the apache/nginx logs?

**Comment by Recouse** [comment] 2016-04-15 08:03
`#0 /var/fmweb/www/fm-web.site/bots/fcobod_bot/Commands/AlertsCommand.php(40): Longman\TelegramBot\Entities\Chat->__construct(107254408)
#1 /var/fmweb/www/fm-web.site/bots/fcobod_bot/vendor/longman/telegram-bot/src/Commands/Command.php(133): Longman\TelegramBot\Commands\SystemCommands\AlertsCommand->execute()
#2 /var/fmweb/www/fm-web.site/bots/fcobod_bot/vendor/longman/telegram-bot/src/Telegram.php(513): Longman\TelegramBot\Commands\Command->preExecute()
#3 /var/fmweb/www/fm-web.site/bots/fcobod_bot/vendor/longman/telegram-bot/src/Commands/SystemCommands/GenericmessageCommand.php(62): Longman\TelegramBot\Telegram->executeCommand('alert" while reading response header from upstream, client: 149.154.167.211, server: fm-web.site, request: "POST /bots/fcobod_bot/hook.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "fm-web.site"
2016/04/13 15:18:48 [error] 22991#22991: *104306 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(fcobob_bot.log): failed to open stream: Permission denied in /var/fmweb/www/fm-web.site/bots/fcobod_bot/vendor/longman/telegram-bot/src/Request.php on line 126
PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Longman\TelegramBot\Entities\Chat::__construct() must be of the type array, integer given, called in /var/fmweb/www/fm-web.site/bots/fcobod_bot/Commands/AlertsCommand.php on line 40 and defined in /var/fmweb/www/fm-web.site/bots/fcobod_bot/vendor/longman/telegram-bot/src/Entities/Chat.php:25
`

**Comment by CrazyRedScorp** [comment] 2016-04-15 09:30
Set permissions 755 and apache:apache (the user is running on Apache) to folder for your path /var/fmweb/www/***/bots/fcobod_bot (folder where is file hook.php). In this folder will be stored fcobob_bot.log. The next step - to send text for bot and check the file. Maybe you have a problem with some of the command files.

**Comment by Recouse** [comment] 2016-04-15 16:41
Bot is working now.

**Comment by Recouse** [comment] 2016-04-16 18:01
It's again repeated just with another bot.
Nginx logs are empty.

**Comment by jacklul** [comment] 2016-04-17 12:05
Are requests from Telegram API '200 OK'?
I had similar issues with weird host configuration where it was returning 404 errors on requests from API, I had to place 'header("HTTP/1.1 200 OK");' on top of hook.php to force it to work.

**Comment by Recouse** [comment] 2016-04-17 15:05
@jacklul it didn't help.

**Comment by antonanton** [comment] 2016-04-26 10:51
@Recouse did u solved it? How did u solved the problem first time?

**Comment by Recouse** [comment] 2016-04-26 10:55
I set custom commands path in hook.php but didn't add Commands folder. A second time i send wrong request in command file.

**Comment by antonanton** [comment] 2016-04-26 11:03
@Recouse set web hook and add functions 
`require __DIR__ . '/vendor/autoload.php';

$API_KEY = 'key';
$BOT_NAME = 'name';
$commands_path = __DIR__ . '/Commands/';
try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);
    echo $telegram->getBotName();
    echo $telegram->getApiKey();
    //// Enable MySQL
    //$telegram->enableMySQL($mysql_credentials);

    //// Enable MySQL with table prefix
    //$telegram->enableMySQL($mysql_credentials, $BOT_NAME . '_');

    //// Add an additional commands path
    $telegram->addCommandsPath($commands_path);

    //// Here you can enable admin interface for the channel you want to manage
    //$telegram->enableAdmins(['your_telegram_id']);
    //$telegram->setCommandConfig('sendtochannel', ['your_channel' => '@type_here_your_channel']);

    //// Here you can set some command specific parameters,
    //// for example, google geocode/timezone api key for date command:
    //$telegram->setCommandConfig('date', ['google_api_key' => 'your_google_api_key_here']);

    //// Logging
    $telegram->setLogRequests(true);
    $telegram->setLogPath($BOT_NAME . '.log');
    $telegram->setLogVerbosity(3);

    //// Set custom Upload and Download path
    //$telegram->setDownloadPath('../Download');
    //$telegram->setUploadPath('../Upload');

    // Handle telegram webhook request
    $telegram->handle();
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    // Silence is golden!
    // log telegram errors
    echo $e;
}
`
when I access hook.php from browser it returns me name and api but not handle commands. I copy pasted commands from example. Nothing works.

**Comment by Recouse** [comment] 2016-04-26 14:00
You don't have to run hook.php from the browser. You have to run set.php with correct link to hook.php inside.

**Comment by antonanton** [comment] 2016-04-26 14:02
@Recouse ye i know i just made it to test is it working or not. but anyway bot do not respond

**Comment by Recouse** [comment] 2016-04-26 14:29
You add a Commands folder?

**Comment by antonanton** [comment] 2016-04-26 14:31
Yes i did. Don't know what's the problem. Any way to check my bot works or not?

**Comment by Recouse** [comment] 2016-04-26 14:37
You have a SSL certificate? :smiley:

**Comment by antonanton** [comment] 2016-04-26 14:39
yes i made one using letsencrypt for my domain kazakov.io(i host it on digital ocean) and i made selfmade ssl using http://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl this. Any ideas?

**Comment by Recouse** [comment] 2016-04-26 14:43
I've never used selfmade ssl. I tried once, but it didn't work.

**Comment by antonanton** [comment] 2016-04-26 14:44
Which one do u use and were u host ur bot?

**Comment by Recouse** [comment] 2016-04-26 14:50
I host my bot on my vps.

**Comment by antonanton** [comment] 2016-04-26 14:52
I use digital ocean as VPS and apache2 on ubuntu 14 as a server + lets encrypt as ssl certificate

**Comment by Recouse** [comment] 2016-04-26 14:56
Can you send me your set.php and hook.php to my [telegram](https://telegram.me/Recouse)?

**Comment by noplanman** [comment] 2016-04-26 19:13
@Recouse Thanks for your effort in solving this, but it makes more sense to post it here so that we can all learn and fix it, should it be some missing step in the readme or something 😉

**Comment by antonanton** [comment] 2016-04-26 19:16
@noplanman Thank you! We solved my problem I will show what was wrong tomorrow.

**Comment by KingDragonX** [comment] 2016-04-28 11:19
@antonanton i have the same problem, i'd glad to see how did you solve this too.

**Comment by antonanton** [comment] 2016-04-29 07:04
Okay, let mt tell what we've done to fix this issue.

**Comment by antonanton** [comment] 2016-04-29 07:14
@KingDragonX ,Ok let me tell what we've done to make bot work.
- Check your SSL certificate. If you have domain with SSL, like mine (https://kazakov.io) you should use  `$result = $telegram->setWebHook($hook_url);`, if you have self made SSL use `$result = $telegram->setWebHook($hook_url, $path_certificate);`. Make sure you have one of this lines.

- Create new bot to make sure you haven't any webhooks binded.

- Check path to Commands folder

- Go to ~/set.php from your browser it must print Webhook was set.

Feel free to ask me.

**Comment by noplanman** [comment] 2016-04-29 17:12
> Create new bot to make sure you haven't any webhooks binded

That's what the `unset.php` file is for, to (you guessed it!) **unset** the Webhook.

Apart from that, what you've described is exactly what is in the readme 😃

Or do you have a suggestion on how we could improve the readme so that this doesn't happen to anybody else?

**Comment by antonanton** [comment] 2016-04-29 17:49
@noplanman nope, actually all probs with bot responding caused by some silly mistakes and SSL certificate. Your API works amazing

**Comment by noplanman** [comment] 2016-04-29 18:39
Ok, so I'll close this again for now and hope that people read more carefully 😜

**Closed by noplanman** 2016-04-29 18:39 UTC
